<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

use App\Http\Controllers\LogicController;

class DefaultSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $logic = new LogicController();

        DB::table('kategori')->insert([
            [ // Profil
                'kategori_id' => 1, 
                'kategori_judul_ID' => 'Profil', 
                'kategori_judul_EN' => 'Profile',
                'kategori_slug' => 'profil',
                'kategori_icon' => '<i class="fas fa-school"></i>',
                'kategori_urutan' => 1,
                'kategori_status' => 1,
            ],
            [ // Akademik
                'kategori_id' => 2, 
                'kategori_judul_ID' => 'Akademik', 
                'kategori_judul_EN' => 'Academic',
                'kategori_slug' => 'akademik',
                'kategori_icon' => '<i class="fas fa-graduation-cap"></i>',
                'kategori_urutan' => 2,
                'kategori_status' => 1,
            ], 
            [ // Kemahasiswaan & Alumni
                'kategori_id' => 3, 
                'kategori_judul_ID' => 'Kemahasiswaan & Alumni', 
                'kategori_judul_EN' => 'Student Affairs & Alumni',
                'kategori_slug' => 'kemahasiswaan-dan-alumni',
                'kategori_icon' => '<i class="fa-solid fa-user-tie"></i>',
                'kategori_urutan' => 3,
                'kategori_status' => 1,
            ],
            [ // Penelitian & Pengabdian
                'kategori_id' => 4, 
                'kategori_judul_ID' => 'Penelitian & Pengabdian', 
                'kategori_judul_EN' => 'Research & Community Service',
                'kategori_slug' => 'penelitian-dan-pengabdian',
                'kategori_icon' => '<i class="fas fa-atom"></i>',
                'kategori_urutan' => 4,
                'kategori_status' => 1,
            ],
            [ // Jaminan Mutu
                'kategori_id' => 5, 
                'kategori_judul_ID' => 'Jaminan Mutu', 
                'kategori_judul_EN' => 'Quality Assurance',
                'kategori_slug' => 'jaminan-mutu',
                'kategori_icon' => '<i class="fas fa-medal"></i>',
                'kategori_urutan' => 5,
                'kategori_status' => 1,
            ],
            [ // Berita
                'kategori_id' => 6, 
                'kategori_judul_ID' => 'Informasi', 
                'kategori_judul_EN' => 'Informations',
                'kategori_slug' => 'informasi',
                'kategori_icon' => '<i class="fa-solid fa-newspaper"></i>',
                'kategori_urutan' => 6,
                'kategori_status' => 1,
            ],
            [ // Kontak
                'kategori_id' => 7, 
                'kategori_judul_ID' => 'Kontak', 
                'kategori_judul_EN' => 'Contact',
                'kategori_slug' => 'kontak',
                'kategori_icon' => '<i class="fa-solid fa-phone"></i>',
                'kategori_urutan' => 7,
                'kategori_status' => 1,
            ],
        ]);

        DB::table('menu')->insert([
            [ // Sejarah
                'menu_id' => 1,
                'menu_judul_ID' => 'Sejarah',
                'menu_judul_EN' => 'History',
                'menu_slug' => 'sejarah',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang sejarah Ilmu Politik dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about history of Political Science in English',
                'menu_urutan' => 1,
                'menu_status' => 0,
                'menu_as' => 1,
                'menu_show' => 1,
            ], 
            [ // Visi, Misi, & Tujuan Kompetensi
                'menu_id' => 2,
                'menu_judul_ID' => 'Visi, Misi, & Tujuan Kompetensi',
                'menu_judul_EN' => 'Vision, Mission, & Competency Goals',
                'menu_slug' => 'visi-misi-tujuan-kompetensi',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang visi, misi, dan tujuan kompetensi dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about vision, mission, and competency goals in English.',
                'menu_urutan' => 2,
                'menu_status' => 0,
                'menu_as' => 1,
                'menu_show' => 1,
            ],
            [ // Visi Keilmuan
                'menu_id' => 3,
                'menu_judul_ID' => 'Visi Keilmuan',
                'menu_judul_EN' => 'Scientific Vision',
                'menu_slug' => 'visi-keilmuan',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang visi keilmuan dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about scientific vision in English.',
                'menu_urutan' => 3,
                'menu_status' => 0,
                'menu_as' => 1,
                'menu_show' => 1,
            ],
            [ // Struktur Organisasi
                'menu_id' => 4,
                'menu_judul_ID' => 'Struktur Organisasi',
                'menu_judul_EN' => 'Organizational Structure',
                'menu_slug' => 'struktur-organisasi',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang struktur organisasi dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about organizational structure in English.',
                'menu_urutan' => 4,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],
            [ // Renstra & Proker
                'menu_id' => 5,
                'menu_judul_ID' => 'Renstra & Proker',
                'menu_judul_EN' => 'Strategic Plan & Work Program',
                'menu_slug' => 'renstra-proker',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang rencana strategis dan program kerja dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about strategic plan and work program in English.',
                'menu_urutan' => 5,
                'menu_status' => 0,
                'menu_as' => 1,
                'menu_show' => 1,
            ],
            [ // Dosen
                'menu_id' => 6,
                'menu_judul_ID' => 'Dosen',
                'menu_judul_EN' => 'Lecturers',
                'menu_slug' => 'dosen',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang daftar dosen dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about list of lecturers in English.',
                'menu_urutan' => 6,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],
            [ // Tenaga Pendidik
                'menu_id' => 7,
                'menu_judul_ID' => 'Tenaga Pendidik',
                'menu_judul_EN' => 'Educational Staff',
                'menu_slug' => 'tenaga-pendidik',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang tenaga pendidik dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about educational staff in English.',
                'menu_urutan' => 7,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],
        ]);
        DB::table('kategori_to_menu')->insert([
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 1,
                'menu_id' => 1,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 1,
                'menu_id' => 2,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 1,
                'menu_id' => 3,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 1,
                'menu_id' => 4,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 1,
                'menu_id' => 5,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 1,
                'menu_id' => 6,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 1,
                'menu_id' => 7,
            ],
        ]);

        DB::table('menu')->insert([
            [ // Status Sertifikat & Akreditasi
                'menu_id' => 8,
                'menu_judul_ID' => 'Status Sertifikat & Akreditasi',
                'menu_judul_EN' => 'Certificate & Accreditation Status',
                'menu_slug' => 'status-sertifikat-akreditasi',
                'menu_gambar' => 'assets/images/dynamic/akreditasi.png',
                'menu_isi_ID' => 'Isi tentang status sertifikat dan akreditasi dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about certificate and accreditation status in English.',
                'menu_urutan' => 1,
                'menu_status' => 0,
                'menu_as' => 1,
                'menu_show' => 1,
            ],
            [ // Informasi Penerimaan Mahasiswa Baru
                'menu_id' => 9,
                'menu_judul_ID' => 'Informasi Penerimaan Mahasiswa Baru',
                'menu_judul_EN' => 'New Student Admission Information',
                'menu_slug' => 'informasi-penerimaan-mahasiswa-baru',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang informasi penerimaan mahasiswa baru dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about new student admission information in English.',
                'menu_urutan' => 2,
                'menu_status' => 0,
                'menu_as' => 2,
                'menu_show' => 1,
            ],
            [ // Kurikulum
                'menu_id' => 10,
                'menu_judul_ID' => 'Kurikulum',
                'menu_judul_EN' => 'Curriculum',
                'menu_slug' => 'kurikulum',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang kurikulum dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about curriculum in English.',
                'menu_urutan' => 3,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],
            [ // Mata Kuliah
                'menu_id' => 11,
                'menu_judul_ID' => 'Mata Kuliah',
                'menu_judul_EN' => 'Courses',
                'menu_slug' => 'mata-kuliah',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang mata kuliah dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about courses in English.',
                'menu_urutan' => 4,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],
            [ // Fokus Riset Dosen
                'menu_id' => 12,
                'menu_judul_ID' => 'Fokus Riset Dosen',
                'menu_judul_EN' => 'Lecturers’ Research Focus',
                'menu_slug' => 'fokus-riset-dosen',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang fokus riset dosen dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about lecturers’ research focus in English.',
                'menu_urutan' => 5,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],
            [ // Kalender Akademik
                'menu_id' => 13,
                'menu_judul_ID' => 'Kalender Akademik',
                'menu_judul_EN' => 'Academic Calendar',
                'menu_slug' => 'kalender-akademik',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang kalender akademik dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about academic calendar in English.',
                'menu_urutan' => 6,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],
            [ // Layanan Akademik
                'menu_id' => 14,
                'menu_judul_ID' => 'Layanan Akademik',
                'menu_judul_EN' => 'Academic Services',
                'menu_slug' => 'layanan-akademik',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang layanan akademik dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about academic services in English.',
                'menu_urutan' => 7,
                'menu_status' => 0,
                'menu_as' => 2,
                'menu_show' => 1,
            ],
        ]);
        
        DB::table('kategori_to_menu')->insert([
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 2,
                'menu_id' => 8,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 2,
                'menu_id' => 9,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 2,
                'menu_id' => 10,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 2,
                'menu_id' => 11,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 2,
                'menu_id' => 12,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 2,
                'menu_id' => 13,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 2,
                'menu_id' => 14,
            ],
        ]);

        DB::table('menu')->insert([
            [ // Prestasi Mahasiswa
                'menu_id' => 15,
                'menu_judul_ID' => 'Prestasi Mahasiswa',
                'menu_judul_EN' => 'Student Achievements',
                'menu_slug' => 'prestasi-mahasiswa',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang prestasi mahasiswa dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about student achievements in English.',
                'menu_urutan' => 1,
                'menu_status' => 0,
                'menu_as' => 2,
                'menu_show' => 1,
            ],
            [ // Organisasi Kemahasiswaan
                'menu_id' => 16,
                'menu_judul_ID' => 'Organisasi Kemahasiswaan',
                'menu_judul_EN' => 'Student Organizations',
                'menu_slug' => 'organisasi-kemahasiswaan',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang organisasi kemahasiswaan dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about student organizations in English.',
                'menu_urutan' => 2,
                'menu_status' => 0,
                'menu_as' => 2,
                'menu_show' => 1,
            ],
            [ // Kegiatan Mahasiswa
                'menu_id' => 17,
                'menu_judul_ID' => 'Kegiatan Mahasiswa',
                'menu_judul_EN' => 'Student Activities',
                'menu_slug' => 'kegiatan-mahasiswa',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang kegiatan mahasiswa dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about student activities in English.',
                'menu_urutan' => 3,
                'menu_status' => 0,
                'menu_as' => 2,
                'menu_show' => 1,
            ],
            [ // Informasi Beasiswa
                'menu_id' => 18,
                'menu_judul_ID' => 'Informasi Beasiswa',
                'menu_judul_EN' => 'Scholarship Information',
                'menu_slug' => 'informasi-beasiswa',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang informasi beasiswa dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about scholarship information in English.',
                'menu_urutan' => 4,
                'menu_status' => 0,
                'menu_as' => 2,
                'menu_show' => 1,
            ],
            [ // Informasi Wisuda
                'menu_id' => 19,
                'menu_judul_ID' => 'Informasi Wisuda',
                'menu_judul_EN' => 'Graduation Information',
                'menu_slug' => 'informasi-wisuda',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang informasi wisuda dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about graduation information in English.',
                'menu_urutan' => 5,
                'menu_status' => 0,
                'menu_as' => 1,
                'menu_show' => 1,
            ],
            [ // Informasi Alumni
                'menu_id' => 20,
                'menu_judul_ID' => 'Informasi Alumni',
                'menu_judul_EN' => 'Alumni Information',
                'menu_slug' => 'informasi-alumni',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang informasi alumni dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about alumni information in English.',
                'menu_urutan' => 6,
                'menu_status' => 0,
                'menu_as' => 2,
                'menu_show' => 1,
            ],
            [ // Profil Alumni
                'menu_id' => 21,
                'menu_judul_ID' => 'Profil Alumni',
                'menu_judul_EN' => 'Alumni Profile',
                'menu_slug' => 'profil-alumni',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang profil alumni dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about alumni profile in English.',
                'menu_urutan' => 7,
                'menu_status' => 0,
                'menu_as' => 2,
                'menu_show' => 1,
            ],
        ]);
        
        DB::table('kategori_to_menu')->insert([
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 3,
                'menu_id' => 15,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 3,
                'menu_id' => 16,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 3,
                'menu_id' => 17,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 3,
                'menu_id' => 18,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 3,
                'menu_id' => 19,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 3,
                'menu_id' => 20,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 3,
                'menu_id' => 21,
            ],
        ]);
        
        DB::table('menu')->insert([
            [ // Riset & Publikasi
                'menu_id' => 22,
                'menu_judul_ID' => 'Riset & Publikasi',
                'menu_judul_EN' => 'Research & Publications',
                'menu_slug' => 'riset-publikasi',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang riset dan publikasi dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about research and publications in English.',
                'menu_urutan' => 1,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],
            [ // Hasil Penelitian
                'menu_id' => 23,
                'menu_judul_ID' => 'Hasil Penelitian',
                'menu_judul_EN' => 'Research Results',
                'menu_slug' => 'hasil-penelitian',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang hasil penelitian dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about research results in English.',
                'menu_urutan' => 2,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],
            [ // Hasil Pengabdian
                'menu_id' => 24,
                'menu_judul_ID' => 'Hasil Pengabdian',
                'menu_judul_EN' => 'Community Service Results',
                'menu_slug' => 'hasil-pengabdian',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang hasil pengabdian dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about community service results in English.',
                'menu_urutan' => 3,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],
        ]);
        
        DB::table('kategori_to_menu')->insert([
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 4,
                'menu_id' => 22,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 4,
                'menu_id' => 23,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 4,
                'menu_id' => 24,
            ],
        ]);
        




        DB::table('menu')->insert([
            [ // Audit Internal & Eksternal
                'menu_id' => 25,
                'menu_judul_ID' => 'Audit Internal & Eksternal',
                'menu_judul_EN' => 'Internal & External Audit',
                'menu_slug' => 'audit-internal-eksternal',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang audit internal & eksternal dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about internal & external audit in English.',
                'menu_urutan' => 1,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],
            [ // Organisasi Penjaminan Mutu
                'menu_id' => 26,
                'menu_judul_ID' => 'Organisasi Penjaminan Mutu',
                'menu_judul_EN' => 'Quality Assurance Organization',
                'menu_slug' => 'organisasi-penjaminan-mutu',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang organisasi penjaminan mutu dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about quality assurance organization in English.',
                'menu_urutan' => 2,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],
            [ // Sistem Dokumen
                'menu_id' => 27,
                'menu_judul_ID' => 'Sistem Dokumen',
                'menu_judul_EN' => 'Document System',
                'menu_slug' => 'sistem-dokumen',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang sistem dokumen dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about document system in English.',
                'menu_urutan' => 3,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],
            [ // Tinjauan Manajemen
                'menu_id' => 28,
                'menu_judul_ID' => 'Tinjauan Manajemen',
                'menu_judul_EN' => 'Management Review',
                'menu_slug' => 'tinjauan-manajemen',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang tinjauan manajemen dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about management review in English.',
                'menu_urutan' => 4,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],
            [ // Standar Operasional Prosedur
                'menu_id' => 29,
                'menu_judul_ID' => 'Standar Operasional Prosedur',
                'menu_judul_EN' => 'Standard Operating Procedure',
                'menu_slug' => 'standar-operasional-prosedur',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang standar operasional prosedur dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about standard operating procedure in English.',
                'menu_urutan' => 5,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],
            [ // Pengukuran Pencapaian Standar Kompetensi Lulusan
                'menu_id' => 30,
                'menu_judul_ID' => 'Pengukuran Pencapaian Standar Kompetensi Lulusan',
                'menu_judul_EN' => 'Graduate Competency Standard Achievement Measurement',
                'menu_slug' => 'pengukuran-pencapaian-kompetensi',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang pengukuran pencapaian standar kompetensi lulusan dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about graduate competency standard achievement measurement in English.',
                'menu_urutan' => 6,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],
            [ // Hasil Kepuasan Pengguna Lulusan
                'menu_id' => 31,
                'menu_judul_ID' => 'Hasil Kepuasan Pengguna Lulusan',
                'menu_judul_EN' => 'Graduate User Satisfaction Results',
                'menu_slug' => 'hasil-kepuasan-pengguna-lulusan',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang hasil kepuasan pengguna lulusan dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about graduate user satisfaction results in English.',
                'menu_urutan' => 7,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],


        ]);
        DB::table('kategori_to_menu')->insert([
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 5,
                'menu_id' => 25,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 5,
                'menu_id' => 26,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 5,
                'menu_id' => 27,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 5,
                'menu_id' => 28,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 5,
                'menu_id' => 29,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 5,
                'menu_id' => 30,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 5,
                'menu_id' => 31,
            ],
        ]);
        
        DB::table('menu')->insert([
            [ // Berita Program Studi
                'menu_id' => 32,
                'menu_judul_ID' => 'Berita Program Studi',
                'menu_judul_EN' => 'Study Program News',
                'menu_slug' => 'berita',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang berita program studi dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about study program news in English.',
                'menu_urutan' => 1,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],
            [ // Pengumuman
                'menu_id' => 33,
                'menu_judul_ID' => 'Pengumuman',
                'menu_judul_EN' => 'Announcements',
                'menu_slug' => 'pengumuman',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang pengumuman dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about announcements in English.',
                'menu_urutan' => 2,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],
            [ // Kegiatan
                'menu_id' => 34,
                'menu_judul_ID' => 'Kegiatan',
                'menu_judul_EN' => 'Activities',
                'menu_slug' => 'kegiatan',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang kegiatan dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about activities in English.',
                'menu_urutan' => 3,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],
            [ // Galeri
                'menu_id' => 35,
                'menu_judul_ID' => 'Galeri',
                'menu_judul_EN' => 'Gallery',
                'menu_slug' => 'galeri',
                'menu_gambar' => null,
                'menu_isi_ID' => 'Isi tentang galeri dalam bahasa Indonesia.',
                'menu_isi_EN' => 'Content about gallery in English.',
                'menu_urutan' => 4,
                'menu_status' => 0,
                'menu_as' => 0,
                'menu_show' => 1,
            ],
        ]);
        
        DB::table('kategori_to_menu')->insert([
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 6,
                'menu_id' => 32,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 6,
                'menu_id' => 33,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 6,
                'menu_id' => 34,
            ],
            [
                'relation_id' => $logic->generateUniqueId('kategori_to_menu', 'relation_id'),
                'kategori_id' => 6,
                'menu_id' => 35,
            ],
        ]);
        
    }
}
